### ISSUE TITLE
Server Updates for Presentation March 6

### ISSUE THREAD

**Issue by EvanKluger** [CooperExchange/server#9]
**Server Repo:**

**Working Environment for Presentation:**
Make a Shell Script that Encapsulates and Runs the Back-End Server for Presentation

On Running the Shell Script will Build the Backend and Database and offer the User the Following Options: 

**1**
Register – 1
Login – 2
Registration-Random - 3

**2**
If User Enters Register it will ask User for Registration Information
If User Enters Login it will ask User for Login Information
If User Enters Registration Random it will auto give Username and Password

**3**
After User Registers/Logins it will offer the following options
Withdraw - 1
Deposit - 2
Update Settings - 3
Buy - 4
Sell - 5
View Portfolio - 6

**4**
Whichever action User choses we will need to initiate that action and return results. 

**Demo Endpoints:**

**Registration (POST/register an account)**
Completed: Yes
Testiest: No

Error Cases:
User Can’t make an Account with Same Name as Another – Completed: No

**Registration -Random (POST/register a random account)**
Completed: Yes
Tested: No

Error Cases:

**Login (POST/handle authentication)**
Completed: Yes
Tested: No

**Deposit (POST/increase cash balance)**
Completed: Yes
Tested: No

Error Cases:

**Withdraw (POST/decrease cash balance)**
Completed: Yes
Tested: No

Error Cases:

**Update (POST/update user credentials)**
Completed: Yes
Tested: No

Error Cases:

**Reset (DELETE/reset the user trades and balance)**
Completed: Yes
Tested: No

Error Cases:

**Buy (POST/purchase an asset)**
Completed: Yes
Tested: No

Error Cases:
User Can’t Make a Trade for a Symbol That does not Exist – Completed: No
User Can’t make a Trade for an Asset Greater than their Current Balance – Completed: No

**Sell (POST/sell an asset)**
Completed: Yes
Tested: No

Error Cases:
User Can’t Make a Sell for a Symbol that does not Exist – Completed: No
User Can’t Sell Something that They do Not have or More of Something than they have – Completed: No

**Portfolio (GET/retrieve user portfolio and balance)**
Completed: No
Tested: No

Error Cases:
User Can’t Make a Sell for a Symbol that does not Exist – Completed: No
User Can’t Sell Something that They do Not have or More of Something than they have – Completed: No

**Comment by bobleesj** [comment]
Hi Evan, for the demo, I was planning to just use the API request tool like here https://reqbin.com/ which I have used to build what I have done so far. 

Are you interested in building a Shell script? That would be extra resources for you to build it. If you can build it before Saturday, I am happy to go with it. Please let us know your timeline.
